development:
  cloud_name: hiromataba
  api_key: '598853614344959'
  api_secret: JkslDCUcdBhAhPL6NcAiYa3KKRE
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: hiromataba
  api_key: '598853614344959'
  api_secret: JkslDCUcdBhAhPL6NcAiYa3KKRE
  enhance_image_tag: true
  static_file_support: true